id: P004387
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:17:19.807421
source_metadata:
  id: bdr:W29567
  title: རྡོ་རྗེའི་ཚིག་རྐང་།
  author: ''
  volumes:
    3f5dd8bd3f7c4d42bdbea7a95b59ac90:
      image_group_id: I1KG10217
      title: ''
      volume_number: 1
      total_pages: 576
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
